# docs/_config.yml

title: iNUX Interactive Documents
description: An overview about iNUX Jupyter Notebooks and Streamlit Apps for interactive education
theme: just-the-docs

url: "https://navneetsinha-ns.github.io"   # <-- user root ONLY
baseurl: "/Jupyter-Notebooks"             # <-- repo name with leading slash

aux_links:
  "Jupyter-Notebooks on GitHub": https://github.com/navneetsinha-ns/Jupyter-Notebooks

sass:
  sass_dir: _sass
  style: compressed

color_scheme: iNUX_colors1
#logo: "/assets/images/iNUX_wLogo.png"
